### ISSUE TITLE
Merisää

### ISSUE THREAD

**Issue by juffe84** [TheJapsu1/vaasa-weather-app#1]
Merisää play button is not working.

**Comment by japsuu** [comment]
Ilmatieteenlaitos does not provide an API to fetch the marine weather as an audio file.
The "Uusin Merisää" section has been removed, until they provide one.

**Comment by japsuu** [comment]
The latest release has been updated with the changes:
https://github.com/japsuu/vaasa-weather-app/releases/tag/v1.1
